HH-152: fix: open external links to a new tab
City-of-Helsinki/hobbies-helsinki pull request #41
Opened 2022-08-24 15:03 UTC by nenonja

## Description
Open external links to a new tab
https://helsinkisolutionoffice.atlassian.net/browse/HH-152
## Issues

### Closes

**[DEV-XXX](https://helsinkisolutionoffice.atlassian.net/browse/DEV-XXX):**

### Related

## Testing

### Automated tests

### Manual testing

## Screenshots

## Additional notes

2022-08-26 08:13 UTC, nikomakela requested changes
The code changes looks good to me!

The react-helsinki-headless-cms needs to be republished from the latest build, or otherwise the changes related to archive page will be overridden in the main branch.

See: https://www.npmjs.com/package/react-helsinki-headless-cms

2022-08-26 08:13 UTC, nikomakela commented on package.json
> +    "react-helsinki-headless-cms": "1.0.0-alpha2-canary-6084e6e",
This might need a new release, so it does not break the changes that are done later.

2022-09-05 11:55 UTC, melniiv approved these changes

2022-09-05 13:41 UTC, nikomakela approved these changes

2022-09-05 13:43 UTC, merged